### ISSUE TITLE
Issue with Connect Wallet for Depin

### ISSUE THREAD

**Issue by SanghamitraBhowmick1993** [MXCzkEVM/depinscriptions#3]
https://www.notion.so/wannsee-roadmap/Issue-with-Connect-Wallet-for-Depin-e87ca32043ae464ba120c5699c065b9b

**Comment by hairyf** [comment]
Geneva can now be used normally

**Comment by SanghamitraBhowmick1993** [comment]
This is not working still 

![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/3fc361d9-8921-466e-bae2-eb35018b8fda)

**Comment by hairyf** [comment]
what doesn't have a work?

**Comment by SanghamitraBhowmick1993** [comment]
added a video of the issue here

https://github.com/MXCzkEVM/depinscriptions/assets/93600163/954eb131-28e8-4b9c-90b9-7d3f6d15f317

**Comment by hairyf** [comment]
Oh, are you saying that the option to connect to the wallet is missing

**Comment by hairyf** [comment]
I tried to fix it, please try again

**Comment by SanghamitraBhowmick1993** [comment]
The connection works flawlessly with AXS and OKH, but when attempting to connect using Metamask, the page just reloads without establishing a connection

![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/a59b3d44-9dfd-4ffd-91e2-e2d1705f9546)

**Comment by SanghamitraBhowmick1993** [comment]
Working as expected, hence closing this issue
