### ISSUE TITLE
The Depinscriptions Dapp appears to not have been deployed yet, as it gives a 404 error

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/depinscriptions#4]
![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/100bed15-710f-4185-b78c-6dc146df400c)

**Comment by SanghamitraBhowmick1993** [comment]
this is working as expected


![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/065b5565-b478-4508-bc87-3bcca69b3b68)
