### ISSUE TITLE
Token Deployment Not Visible in 'In Progress' Screen for Depinscriptions

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/depinscriptions#6]
Upon attempting to deploy a token from the token screen, the token is not appearing in the 'In Progress' screen for depinscriptions. This discrepancy prevents users from tracking the deployment progress of the token and may lead to confusion regarding the status of the deployment process

![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/f229227a-095b-4160-825f-d66d3cfbe1e6)

![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/13bac5f3-6ebf-4cbf-b04d-956a782d2a4d)

Same was observed for transfers

![Image](https://github.com/MXCzkEVM/depinscriptions/assets/93600163/cf324a1c-41eb-4937-9fd7-ae9819469136)

**Comment by hairyf** [comment]
fixed

**Comment by hairyf** [comment]
The length of the server index does not match the length of the geneva block, resulting in infinite skip scanning. This issue has been fixed

![Image](https://github.com/MXCzkEVM/depinscriptions/assets/49724027/ea66cb29-5d4c-44dd-862a-a0e7f1e116d7)

**Comment by SanghamitraBhowmick1993** [comment]
Testing in progress

**Comment by SanghamitraBhowmick1993** [comment]
This is working. Tested Token Deploy, Mint Token and Transfers!!
